import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import "./theme-config.css";
import AuthProvider from "./api/auth/[...nextauth]/Provider";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Gal's Issue Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <AuthProvider>
          <Theme accentColor="violet">
            <NavBar />
            <main className="p-5">{children}</main>
            {/* <ThemePanel /> This pops up the panel for choosing colors*/}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
